const USER_SIGN = "USER_SIGN";
const USER_VERIFY = "USER_VERIFY";
const USER_LOGIN = "USER_LOGIN";
const USER_CHAT = "USER_CHAT";

const ROOM_CREATE = "ROOM_CREATE";
const ROOM_JOIN = "ROOM_JOIN";

export {
  USER_SIGN,
  USER_VERIFY,
  USER_LOGIN,
  USER_CHAT,
  ROOM_CREATE,
  ROOM_JOIN,
};
